services:
  postgres:
    image: postgres:16-alpine
    container_name: notes_db_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      # This volume persists the database data
      - postgres-data:/var/lib/postgresql/data
      # This script will run on initialization from the /database directory
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local
