services:
  backend:
    profiles:
      - prod
    image: exempl4r/cfmn-backend:latest
    container_name: cfmn_backend
    restart: always
    env_file:
      - ./.env
    networks:
      metaploy-network:
        aliases:
          - cfmn_backend
      metaploy-private-network:
    volumes:
      - ./logs:/app/log
      - nginx-config-volume:/etc/nginx/sites-enabled
      - odins-vault:/app/static_files
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  postgres-dev:
    image: postgres:16-alpine
    container_name: cfmn_dev_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_USER}

    profiles:
      - dev

    ports:
      - "5432:5432"
    volumes:
      # This volume persists the database data
      - postgres-data:/var/lib/postgresql/data
      # This script will run on initialization from the /database directory
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

networks:
  metaploy-network:
    external: true
    name: metaploy-network
  metaploy-private-network:
    external: true
    name: metaploy-private-network

volumes:
  postgres-data:
    name: postgres-data
  nginx-config-volume:
    external: true
    name: metaploy-nginx-config-volume
  odins-vault:
    external: true
    name: odins-vault






