services:
  cfmn-backend:
    build: .
    container_name: cfmn-backend
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=cfmn-database
    volumes:
      - ./static:/app/static
      - ./logs:/app/logs
      - nginx-config-volume:/nginx-config
    networks:
      - metaploy-network
      - metaploy-private-network
    depends_on:
      - cfmn-database
    restart: unless-stopped
    entrypoint: ["/app/scripts/postinstall.sh"]

  cfmn-database:
    image: postgres:15
    container_name: cfmn-database
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - cfmn-postgres-data:/var/lib/postgresql/data
    networks:
      - metaploy-private-network
    restart: unless-stopped

volumes:
  cfmn-postgres-data:
  nginx-config-volume:
    external: true
    name: metaploy_nginx-config-volume

networks:
  metaploy-network:
    external: true
    name: metaploy_metaploy-network
  metaploy-private-network:
    external: true
    name: metaploy_metaploy-private-network