services:
  backend:
    image: exempl4r/cfmn-backend
    container_name: cfmn_backend
    restart: always
    env_file:
      - ./.env
    ports:
      - "8085:8085"
    volumes:
      - static-files:/app/static_files
      - logs:/app/log
    networks:
      - cfmn-net

  postgres:
    image: postgres:16-alpine
    container_name: cfmn_db_container
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cfmn-net

volumes:
  postgres-data:
    driver: local
  static-files:
    driver: local
  logs:
    driver: local

networks:
  cfmn-net:
    driver: bridge
